# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#what branch are we watching
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
#watch for pr's
pr: 'none'
#group sequential actions
stages:
  - stage:
    jobs:
      - job: 'build'
        steps:
          - script: dotnet build 'ProjectOne\ProjectOne\ProjectOne.csproj'

      - job: 'test'
        dependsOn: 'build'
        steps:
          - script: 'dotnet test'

      - job: 'publish'
        dependsOn: 'test'
        steps:
          - script: 'dotnet publish'

